### ISSUE TITLE
Update 6

### ISSUE THREAD

**Issue by elMooXos** [BatedUrGonnaDie/Autosplitters#11]
Hi, last update broke the autosplitter, I've tried to figure out by myself the new values but I have a huge lack of skill regarding programming, a help would be greatly appreciated :)

**Comment by BatedUrGonnaDie** [comment]
If you install Cheat Engine and hook it to Refunct, it allows you to see the memory values. From there its about narrowing down the results to only the values you're looking for and updating the variables in the beginning of the scripts to point to the new locations.

**Comment by elMooXos** [comment]
Ok, I managed to progress a bit and find a pointer that seems to work for the "levels" value, it's
int   level               : 0x020D8908, 0x1AC, 0x18, 0x2B4, 0xF0, 0xAC;
It works and I can have a simple splitter like this:
```
state("Refunct-Win32-Shipping")
{
    int   level               : 0x020D8908, 0x1AC, 0x18, 0x2B4, 0xF0, 0xAC;
}

start
{
    return current.level < old.level;
}

split
{
    return current.level > old.level;
}

reset
{
    return current.level < old.level;
}
```



The problem is that I can't have proper resets, as I don't know how to find the value or the adress of your "int reset" variable from your previous work. I guess that there is maybe a reset counter in the game?
